function Hd = Equiripple
%EQUIRIPPLE Returns a discrete-time filter object.

% MATLAB Code
% Generated by MATLAB(R) 24.2 and Signal Processing Toolbox 24.2.
% Generated on: 09-May-2025 21:13:05

% Equiripple Lowpass filter designed using the FIRPM function.

% All frequency values are in Hz (Fs = 32e3 = 32 kHz).
Fs = 32e3;  % Sampling Frequency in Hz

N     = 250;   % Filter order
Fpass = 14.6e3; % Passband frequency in Hz
Fstop = 15e3;   % Stopband frequency in Hz
Wpass = 1;     % Passband weight
Wstop = 1;     % Stopband weight
dens  = 20;    % Density Factor

% Calculate the coefficients using the FIRPM function.
b  = firpm(N, [0 Fpass Fstop Fs/2]/(Fs/2), [1 1 0 0], [Wpass Wstop], ...
           {dens});
Hd = dfilt.dffir(b);

% Visualize frequency response using FVTool 
fvtool(Hd, 'Fs', Fs);



% Plot impulse response from filter coefficients 
figure;
stem(b, 'filled');
title('Impulse Response of the Filter');
xlabel('Sample Index');
ylabel('Amplitude');
grid on;


end
